version: '2'
services:
  elasticsearch:
    build:
      context: docker-elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
        SG_VERSION: $SG_VERSION
    volumes:
      - ./docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./es6/data:/usr/share/elasticsearch/data
      - ./es6/logs:/usr/share/elasticsearch/logs
    ports:`
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk6

  # logstash:
  #   build:
  #     context: docker-elk/logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./docker-elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
  #     - ./es6/logs://usr/share/logstash/logs
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk6
  #   depends_on:
  #     - elasticsearch

  kibana:
    build:
      context: ./docker-elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
        SG_VERSION_KIBANA: $SG_VERSION_KIBANA
    volumes:
      - ./docker-elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk6
    depends_on:
      - elasticsearch

networks:

  elk6:
    driver: bridge
