version: '3.1'
services:
  nginx:
    image: nginx:1.15.9-alpine
    restart: always
    ports:
      - 8201:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro            #映射nginx的配置文件到容器里
      - ./logs/:/var/log/nginx/
      - ./data/:/var/share/nginx/html/                     #映射nginx的网页目录到容器里
      - ./site/:/site/