version: '3.1'
services:
  mysql:
    image: mysql:5.7.22
    hostname: mysql5
    container_name: mysql5
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./conf:/etc/mysql/conf.d
    networks: 
      - local_net
    
networks:
  local_net:
    external: true