version: '3.1'
services:
  mongodb:
    image: mongo:3.6.4
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
      - MONGO_INITDB_DATABASE=admin
    command: mongod
    volumes:
      - ./data/db:/data/db
      - ./conf/:/etc/mongo.conf:ro
      - ./logs:/var/log/mongodb